
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@localhost:5432/postgres
    depends_on:
      - postgres
    networks:
      - monorepo-network

  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:password@localhost:5432/postgres
    depends_on:
      - postgres
    networks:
      - monorepo-network

  ws:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ws
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgresql://postgres:password@localhost:5432/postgres
    depends_on:
      - postgres
    networks:
      - monorepo-network

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - monorepo-network

networks:
  monorepo-network:
    driver: bridge

volumes:
  postgres-data:
